name: Build & Deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          script: |
            cd www/TreeMan
            php artisan down
            git pull
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan optimize:clear
            php artisan migrate
            php artisan optimize
            php artisan up
            
            
      - name: Slack Notification
        uses: act10ns/slack@v1
        with:
          status: ${{job.status}}
          steps: ${{toJson(steps)}}
          channel: '#tree-man'
